### ISSUE TITLE
ESC key selects first option

### ISSUE THREAD

**Issue by ollyskinner** [andrewvasilchuk/vue-accessible-select#18]
If the initial value of a select is undefined, then pressing ESC key after opening the menu (but before making any selection) selects the first option and emits it as an `@input` event.

Is this correct behaviour? My expectation would be that ESC returns the select to whatever state it was in before being interacted with. This works as expected if there is a selected value, but not if there is none.

Thanks, this is a really useful component!

**Comment by andrewvasilchuk** [comment]
@ollyskinner Thank you so much for reporting this issue. I will fix it today or tomorrow and release a new version.

**Comment by andrewvasilchuk** [comment]
@ollyskinner this also happens for all other keys. I will review the component logic in v2.
